data <- "./household_power_consumption.txt"
fulldata <- read.csv(data, header=T, sep=';', na.strings="?", stringsAsFactors=F)
datetime <- strptime(paste(fulldata$Date, fulldata$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
fulldata <- cbind(fulldata, datetime)
fulldata$Date <- as.Date(fulldata$Date, format = "%d/%m/%Y")
fulldata$Time <- format(fulldata$Time, format = "%H:%M:%S")
reqdata <- subset(fulldata, Date == "2007-02-01"|Date == "2007-02-02")
png("plot4.png", height = 480, width = 480)
par(mfrow=c(2,2))
plot(reqdata$datetime, reqdata$Global_active_power, type = "l", ylab = "Global Active Power", xlab = " ")
plot(reqdata$datetime, reqdata$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
plot(reqdata$datetime, reqdata$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = " ")
lines(reqdata$datetime, reqdata$Sub_metering_2, type = "l", col = "red")
lines(reqdata$datetime, reqdata$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
plot(reqdata$datetime, reqdata$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
dev.off()